import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { FileText, Plus, CheckCircle, Clock, Loader2, Download } from 'lucide-react';
import jsPDF from 'jspdf';

const ProjectDetail = () => {
    const { id } = useParams();
    const [project, setProject] = useState(null);
    const [tasks, setTasks] = useState([]);
    const [loading, setLoading] = useState(true);
    const [newTask, setNewTask] = useState('');
    const [generatingContract, setGeneratingContract] = useState(false);

    useEffect(() => {
        fetchProjectData();
    }, [id]);

    const fetchProjectData = async () => {
        try {
            const res = await fetch('http://localhost:3000/api/projects');
            const allProjects = await res.json();
            const p = allProjects.find(p => p.id === id);
            setProject(p);

            // Fetch real tasks
            if (p) {
                const tasksRes = await fetch(`http://localhost:3000/api/tasks?project_id=${id}`);
                const tasksData = await tasksRes.json();
                setTasks(tasksData);
            }
            setLoading(false);
        } catch (error) {
            console.error(error);
            setLoading(false);
        }
    };

    const toggleTaskCompletion = async (taskId) => {
        const taskToUpdate = tasks.find(t => t.id === taskId);
        const newStatus = taskToUpdate.status === 'done' ? 'todo' : 'done';

        // Optimistic update
        setTasks(tasks.map(t =>
            t.id === taskId ? { ...t, status: newStatus } : t
        ));

        try {
            await fetch(`http://localhost:3000/api/tasks/${taskId}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ status: newStatus })
            });
        } catch (error) {
            console.error('Error updating task:', error);
            // Revert on error
            setTasks(tasks.map(t =>
                t.id === taskId ? { ...t, status: taskToUpdate.status } : t
            ));
        }
    };

    const handleAddTask = async (e) => {
        e.preventDefault();
        if (!newTask.trim()) return;

        try {
            const res = await fetch('http://localhost:3000/api/tasks', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    project_id: project.id,
                    title: newTask
                })
            });
            const createdTask = await res.json();
            setTasks([...tasks, createdTask]);
            setNewTask('');
        } catch (error) {
            console.error('Error creating task:', error);
        }
    };

    const generateContract = async () => {
        setGeneratingContract(true);
        try {
            const response = await fetch('http://localhost:3000/api/generate-contract-content', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    clientName: project.clients?.name,
                    projectName: project.name,
                    scope: project.description,
                    budget: project.budget,
                    estimatedDate: project.estimated_end_date
                })
            });
            const data = await response.json();

            // Generate PDF
            const doc = new jsPDF();

            // Header
            doc.setFontSize(22);
            doc.setTextColor(41, 128, 185);
            doc.text("Vaisptech Solutions", 20, 20);

            doc.setFontSize(12);
            doc.setTextColor(100);
            doc.text("Excellence in Technology", 20, 28);

            doc.setDrawColor(200);
            doc.line(20, 35, 190, 35);

            // Content
            doc.setFontSize(16);
            doc.setTextColor(0);
            doc.text("Service Agreement", 105, 50, null, null, "center");

            doc.setFontSize(11);
            const splitText = doc.splitTextToSize(data.content, 170);
            doc.text(splitText, 20, 70);

            // Footer
            doc.setFontSize(10);
            doc.setTextColor(150);
            doc.text("Generated by Vaisptech AI", 105, 280, null, null, "center");

            doc.save(`${project.name.replace(/\s+/g, '_')}_Contract.pdf`);

        } catch (error) {
            console.error('Error generating contract:', error);
            alert('Failed to generate contract');
        } finally {
            setGeneratingContract(false);
        }
    };

    if (loading) return <div className="text-center py-20 text-white">Loading...</div>;
    if (!project) return <div className="text-center py-20 text-white">Project not found</div>;

    return (
        <div>
            <div className="flex justify-between items-start mb-8">
                <div>
                    <h1 className="text-3xl font-bold text-white">{project.name}</h1>
                    <div className="flex items-center gap-4 mt-2 text-gray-400">
                        <span>{project.clients?.name}</span>
                        <span>•</span>
                        <span className="uppercase text-xs font-bold tracking-wider">{project.status}</span>
                    </div>
                </div>
                <button
                    onClick={generateContract}
                    disabled={generatingContract}
                    className="bg-green-600 hover:bg-green-500 text-white px-6 py-3 rounded-lg flex items-center gap-2 transition-colors font-medium shadow-lg shadow-green-500/20 disabled:opacity-50"
                >
                    {generatingContract ? <Loader2 className="animate-spin" size={20} /> : <FileText size={20} />}
                    Generate Service Agreement
                </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Main Content */}
                <div className="lg:col-span-2 space-y-8">

                    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
                        <h2 className="text-xl font-semibold text-white mb-4">Project Scope</h2>
                        <p className="text-gray-400 leading-relaxed">{project.description}</p>
                    </div>

                    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
                        <div className="flex justify-between items-center mb-6">
                            <h2 className="text-xl font-semibold text-white">Tasks</h2>
                            <div className="text-sm text-gray-500">{tasks.filter(t => t.status === 'done').length}/{tasks.length} Completed</div>
                        </div>

                        <div className="space-y-3 mb-6">
                            {tasks.map(task => (
                                <div
                                    key={task.id}
                                    onClick={() => toggleTaskCompletion(task.id)}
                                    className="flex items-center gap-3 p-3 bg-gray-950 rounded-lg border border-gray-800 cursor-pointer hover:bg-gray-900 transition-colors"
                                >
                                    {task.status === 'done' ? (
                                        <CheckCircle className="text-green-500" size={20} />
                                    ) : (
                                        <div className="w-5 h-5 rounded-full border-2 border-gray-600" />
                                    )}
                                    <span className={task.status === 'done' ? 'text-gray-500 line-through' : 'text-gray-300'}>
                                        {task.title}
                                    </span>
                                </div>
                            ))}
                        </div>

                        <form onSubmit={handleAddTask} className="flex gap-2">
                            <input
                                type="text"
                                placeholder="Add a new task..."
                                className="flex-1 bg-gray-950 border border-gray-800 rounded-lg p-3 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                                value={newTask}
                                onChange={e => setNewTask(e.target.value)}
                            />
                            <button type="submit" className="bg-gray-800 hover:bg-gray-700 text-white p-3 rounded-lg transition-colors">
                                <Plus size={20} />
                            </button>
                        </form>
                    </div>
                </div>

                {/* Sidebar Info */}
                <div className="space-y-6">
                    <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
                        <h3 className="text-sm font-medium text-gray-500 mb-4 uppercase tracking-wider">Project Details</h3>
                        <div className="space-y-4">
                            <div>
                                <label className="text-xs text-gray-500">Budget</label>
                                <p className="text-xl font-bold text-white">${project.budget || '0'}</p>
                            </div>
                            <div>
                                <label className="text-xs text-gray-500">Start Date</label>
                                <p className="text-white">{project.start_date || 'TBD'}</p>
                            </div>
                            <div>
                                <label className="text-xs text-gray-500">Est. Completion</label>
                                <p className="text-white">{project.estimated_end_date || 'TBD'}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ProjectDetail;
